#!/bin/bash

# ══════════════════════════════════════════════════════════════════════════════
# CONFIG
# ══════════════════════════════════════════════════════════════════════════════

# - PRELUDE -------------------------------------------------------------------
#   Load core functions and utilities for scripting

    source "$(dirname "$0")/.prelude"

# ══════════════════════════════════════════════════════════════════════════════
# SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

function linux_install {
        printf "\n${GREEN}Install: apt-get packages${NC}\n\n"
        sudo apt-get install git ripgrep
        sudo apt-get install emacs
        sudo apt-get install tmux
    }

    function mac_install {
        printf "\n${GREEN}Install: homebrew packages${NC}\n\n"
        brew install git ripgrep
        brew install coreutils fd
        brew install tmux
        pip3 install tmuxp

        printf "\n${GREEN}Install: emacs${NC}\n\n"
        brew tap d12frosted/emacs-plus
        brew install emacs-plus@28
        ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app
    }

# - MAIN ENTRY -----------------------------------------------------------------

    function main {

        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            linux_install
        elif [[ "$OSTYPE" == "darwin"* ]]; then
            mac_install
        fi

        printf "\n${GREEN}Install: doom emacs${NC}\n\n"
        git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
        ~/.emacs.d/bin/doom install

        printf "\n${GREEN}Install: rust via rustup${NC}\n\n"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

        printf "\n${GREEN}Install: node.js via n${NC}\n\n"
        curl -L https://git.io/n-install | bash

        printf "\n${GREEN}Install: yarn packages${NC}\n\n"
        npm install --global yarn

        printf "\n${GREEN}Install: yarn packages${NC}\n\n"
        yarn global add commitizen
        yarn global add cz-emoji
        yarn global add standard-version
        yarn global add cli-markdown

        printf "\n${GREEN}Install: Finished${NC}\n\n"
    }

# ══════════════════════════════════════════════════════════════════════════════
# EXECUTION
# ══════════════════════════════════════════════════════════════════════════════

# - RUN AS ROOT ----------------------------------------------------------------

    ask_for_sudo main

